# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Pickie"
port: 3000
# The default layout to use for your application (located in
# views/layouts/main.tt)
#layout: "main"
#log: "core"
environment: "development"
# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

daemon: 0
auto_reload: 0

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
   template_toolkit:
     encoding:  'utf8'
     start_tag: '[%'
     end_tag:   '%]'

session: "cookie"
session_cookie_key: "kjsdf04hjfsdkflj12*&(@*jk"

plugins:
  DBIC:
    pickie:
      schema_class: Database::Main
      dsn:  dbi:mysql: dbi:mysql:dbname=pickie;host=localhost
      user: "pickie"
      pass: "pickie"
      options:
        RaiseError: 1
        PrintError: 1
